### ISSUE TITLE
[Breaking Bug] bootstrap.bundle.js Potentially Breaking Other Environments

### ISSUE THREAD

**Issue by junthehacker** [MuradAkh/UofTCourseInfo#3]
Recently while developing a tool for the uni, I noticed that in my development environment, bootstrap dropdown stopped working.
![1](https://user-images.githubusercontent.com/7855724/50460213-a656c100-0939-11e9-8ea3-9dd743b578a4.gif)

After a few minutes of digging, I found that the UofT Course Info plugin is loading another bootstrap js file.

![image](https://user-images.githubusercontent.com/7855724/50460257-09e0ee80-093a-11e9-8a12-5e4afde6ecfd.png)

Which caused this problem.

Might be a good idea to not use bootstrap or have a detection mechanism to not load if there is already one loaded.

At the current state, the plugin must be completely removed for anything to work, which is not ideal.

**Comment by MuradAkh** [comment]
Hey, thanks for opening the issue. I'm currently away but will look into it in couple of days.

Can't really avoid using bootstrap but I will look for a work around. Do you mind sharing some example where this problem can be tested?

**Comment by MuradAkh** [comment]
Thanks for finding this.

The file should only appear in Google search. It's and easy fix and  I will push it in 3 days when I come back from my trip.
