### ISSUE TITLE
Issues with DuckDuckGo

### ISSUE THREAD

**Issue by NyW8** [MuradAkh/UofTCourseInfo#7]
I have DuckDuckGo as my default search engine. I am aware that the extension is not currently compatible with DuckDuckGo, but when a course code is searched (e.g. CSCA08), the page redirects to html.duckduckgo.com with the query '<span class='. 

Expected behaviour: when using an unsupported search engine, the extension simply shouldn't activate.

**Comment by MuradAkh** [comment]
Hi, thanks for the catch, I was able to reproduce it. 
It looks like the extension is trying to generate tooltips for course mentions on the results page, and it creates issues with duckduckgo. 

I will add duckduckgo to the default blacklist for tooltips with the next update. For now I suggest you blacklist it yourself temporairly by:

1. visiting duckduckgo
2. clicking the extension icon, and unchecking "enable tooltips on duckduckgo.com"
3. searching for a course to confirm it works.

Let me know if this works for you

**Comment by MuradAkh** [comment]
I've merged the fix, let me know if the temporary solution above doesn't work. Probably won't release in the next few weeks as I am pretty swamped with work rn.

**Comment by NyW8** [comment]
Amazing, thank you!
